function(vulkan_app app_name source_files)
    if(APPLE)
        add_executable(${app_name} MACOSX_BUNDLE ${source_files})
    elseif(WIN32)
        add_executable(${app_name} WIN32 ${source_files})
    elseif(ANDROID)
        add_executable(${app_name} SHARED ${source_files})
    else()
        add_executable(${CurTargetName} ${CurSources})
    endif()
    target_link_libraries(${app_name} vulkan)
    
#    target_include_directories(${app_name} PUBLIC ../include)
endfunction()
# function(sokol_app app_name glsl_source source_files)
#     sokol_app_shaderless(${app_name} ${source_files})
#     shd_shader(${app_name} ${glsl_source})
# endfunction()